name: Update Football player data

on:
  schedule:
    - cron: '0 9 * * 1' # Runs at 9:00 AM UTC every Monday
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set Kaggle environment variables
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: echo "Kaggle environment variables set"

      # Download data from Kaggle
      - name: Run kaggle_dl.py
        run: python util/kaggle_dl.py

      # Prepare data
      - name: Run analysis.py
        run: python util/analysis.py

      # Update Google Sheets
      - name: Run update_gsheets.py
        run: python util/update_gsheets.py
